### ISSUE TITLE
Migration Question - account_operating_unit

### ISSUE THREAD

**Issue by gdgellatly** [OCA/operating-unit#102]
@jbeficent In account_operating_unit there is a section of code around line 106 of account_move.py that does not seem to match the comment

```python
            # If all move lines point to the same operating unit, there's no
            # need to create a balancing move line
            ou_list_ids = [line.operating_unit_id and
                           line.operating_unit_id.id for line in
                           move.line_ids if line.operating_unit_id]
            if len(ou_list_ids) <= 1:
                continue
```
To my mind this statement is wrong in 2 ways.

1. If there was more than one line with the same ou, it would fail the test despite all pointing to the same ou.
2. If one line doesn't have an ou (is this possible?) and one does, it would pass the test despite not all lines pointing to the same ou.

Sorry its a bit hard for me as I'm doing static code review on v11 ports.  Once it runs I might be able to work out myself, but which is correct, the comment or the code?

**Comment by AaronHForgeFlow** [comment]
@gdgellatly 

IMO  the comment there is correct. However I'm not sure if the code would fail. At least in case all the lines have the same OU it will skip creating  the balancing move line.

**Comment by gdgellatly** [comment]
@aheficent I agree but better to have the code match the comment, besides, there is still a performance impact on a large move.  I changed the code anyway to match in the port, but as I've gone further, I've noticed a few mistakes that I made, so as we merge through I'll be making some small changes to the PR's before submission.
