### ISSUE TITLE
Error in creating purchase order

### ISSUE THREAD

**Issue by ccandito** [OCA/operating-unit#103]
Dear All,
When conforming a quotation for creating a purchase order a following error has occurred:
Error while validating constraint
Configuration error
The Stock moves must be related to a location (source or destination) that belongs to the requesting Operating Unit.

this sounds strange because for the time being only the default main OU has been set and the input location has been assigned to it.
Regards
claudio candito

**Comment by AaronHForgeFlow** [comment]
Dear @ccandito,

I tried to reproduce the issue but it's working fine to me. Can you check if the default location for the picking type is assigned to to the requesting operating unit?

Regards

**Comment by ccandito** [comment]
thanks
now it is working out]
regards
claudio candito
