### ISSUE TITLE
Operating Unit Warehousing Discussion

### ISSUE THREAD

**Issue by gdgellatly** [OCA/operating-unit#104]
Continuation from sidetrack at #94 

@jbeficent I've spent a good chunk of the weekend reviewing current practice, rewriting code and matching it to the requirements under IFRS 8 for segment reporting.  IFRS 8 is quite nice in that it focuses on the internal information used by management, so in that sense we can make operating_unit IFRS compliant (although then I would use the term operating_segment). I think the main difference between where this repo currently stands and IFRS 8 is the focus on the CODM under IFRS.  

So we have issues to cover like an operating segment must generate revenues etc etc but the actual accounting requirement for operating segments is not full IFRS compliance.  Indeed at its most basic it is arguable that a P&L only is sufficient if that is the information used for decisions, but even then in a shared resource environment (bank accounts, warehouses, inter OU trade) we have an allocation issue.

The light bulb moment was realising we have this same issue in a multicompany environment, and companies have long had to deal with this issue.  So if we summarise the primary issue in multicompany consolidated reporting it is fundamentally one of eliminating any transactions which have not left the combined entity, and if we treat operating_segments the same we can acheive this outcome without the needs for the restrictions on bank and cash journals or warehouses.

- An operating segment is responsible for a warehouse as its primary user.
- Beyond COGS we need to consider depreciation, direct labour, freight, etc etc all attributable the operating segment responsible for that warehouse.
- The way we do that in a multicompany environment is of course transfer pricing to cover those costs, and we can apply the same to operating segments (specifically mentioned in IFRS 8 as allowable)

So here is how the journals would look for an MTO sale under anglosaxon where S1 is the stocking segment and S2 is the selling segment, with a self balancing balance sheet.  The goods sold cost $100, and are sold for $200
Apoligies for the messy journals, markdown didn;t make this easy. 

On delivery

| Account | DR | CR | Segment |
|------------|-------:|-------:|-----------|
| Inventory | | 100 | S1 |
| Stock Output | 100 | | S1 |

*To record delivery of goods with a cost of $100 on behalf of S2*

On invoice

| Account | DR | CR | Segment |
|------------|-------:|-------:|-----------|
| Stock Output | | 100 | S1 |
| Xfer Margin (P & L account) | | 10 | S1 |
| Inter OU Debtors (or balancing) | 110 | | S1 |
| COGS | 110 | | S2 |
| Sales | | 200 | S2 |
| Debtors | 200 | | S2 |
| Inter OU Debtors (or balancing) | | 110 | S2 | 

*To record invoice of goods by S2*

Now at this point life goes on as normal.  Payments etc.  On a periodic basis there may be transaction that looks something like (either cash or an inter ou subvention account). Obviously this would be aggregate but you get the idea

| Account | DR | CR | Segment |
|------------|-------:|-------:|-----------|
| Cash / Bank (or subvention) |110 |  | S1 |
| Cash / Bank (or subvention) | | 110 | S2 |
| Inter OU Debtors (or balancing) |110 |  | S2 |
| Inter OU Debtors (or balancing) | | 110 | S1 |

*To record settlement of  inter OU balances at end of period*

Now of course this is a fairly complex example with the inclusion of xfer pricing, but the principle remains the same.  In this case the transaction behaves like a dropship from S1 to S2's customer, but the entries are fairly similar regardless of whether it goes into S2's stock or direct to customer.

What do you think? I think that gets us a self balancing balance sheet without the restrictions on operating units only supplying out of their own warehouses.

**Comment by gdgellatly** [comment]
btw those journals are just one approach, the could just as easily be

On delivery

| Account | DR | CR | Segment |
|------------|-------:|-------:|-----------|
| Inventory | | 100 | S1 |
| Xfer Margin (P & L account) | | 10 | S1 |
| Inter OU Debtors (or balancing) | 110 | | S1 |
| Stock Output | 110 | | S2 |
| Inter OU Debtors (or balancing) | | 110 | S2 | 

*To record delivery of goods with a cost of $100 on behalf of S2*

On invoice

| Account | DR | CR | Segment |
|------------|-------:|-------:|-----------|
| Stock Output | | 110 | S2 |
| COGS | 110 | | S2 |
| Sales | | 200 | S2 |
| Debtors | 200 | | S2 |

*To record invoice of goods by S2*

Which is cleaner from a transaction perspective, but more difficult from elimination.  It also introduces an issue in relation to costing.

**Comment by JordiBForgeFlow** [comment]
Graeme, when I designed the Operating Units I researched a lot on Segment
Reporting and IFRS8, and took it into consideration. I believe that using
the self balancing operating units the system is compliant with IFRS8.

In fact, I found that it is as advanced as SAP's (the big one) segment
reporting approach.

I agree aspect of generating revenues. Now an OU can generate profit only
if it sells to external customers. And you could meet that of the other OU
is an external customer.

But I think that with an inter-OU invoicing module we could easily solve
the issue.

I would not change to operating segments. I thought about it long before
making a decision, and it is not justified. I took the same naming that
Oracle does.

Anyway, I am happy that we're having such debate!

On Nov 12, 2017 9:05 AM, "Graeme Gellatly" <notifications@github.com> wrote:

btw those journals are just one approach, the could just as easily be

On delivery
Account DR CR Segment
Inventory 100 S1
Xfer Margin (P & L account) 10 S1
Inter OU Debtors (or balancing) 110 S1
Stock Output 110 S2
Inter OU Debtors (or balancing) 110 S2

*To record delivery of goods with a cost of $100 on behalf of S2*

On invoice
Account DR CR Segment
Stock Output 110 S2
COGS 110 S2
Sales 200 S2
Debtors 200 S2

*To record invoice of goods by S2*

Which is cleaner from a transaction perspective, but more difficult from
elimination. It also introduces an issue in relation to costing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OCA/operating-unit/issues/104#issuecomment-343720343>,
or mute the thread

**Comment by gdgellatly** [comment]
Hi Jordi,

Just an FYI I'm mocking up a final version of the above, and trying to keep it all compatible, but in doing so have found that the entire Odoo 11 stock valuation is essentially broken, so awaiting on bug fixes as how they fix it will change the code a lot.

**Comment by JordiBForgeFlow** [comment]
Yes, stock valuation.. OMG.... Ask them howndo you revaluate inventory?...
I am so scared about this change...

**Comment by gdgellatly** [comment]
Jordi,

Check this bug report, they are fixing a lot of valuation things right now so its a good chance to get those requests in, but oh my reading some of the changes there have been some big oversights.

https://github.com/odoo/odoo/issues/20892

**Comment by gdgellatly** [comment]
@jbeficent Below is the document I sent into senior management with the final approach that got signed off.  As you can see, it is possible to do, without the warehouse restrictions and this is the way I am going.  In essence we have 2 self balancing accounts rather than one.  One is on the P&L, the other is a Payable in current liabilities (I chose payable because otherwise if a KPI was on ROA or ROE for an operating unit they could in theory massage the number if it was a receivable).

---Begin mail
I spoke briefly about these during the meeting, and the deeper I get, the answer to more and more problems they are.  But they are really hard work to get just right.

For the most part our segments will be geographic, with a Head Office segment as well to handle recharges, rebates, royalties etc.

Using operating units we can for example have Christchurch only see Christchurch customers, only Head Office and Waikato see Waikato's centrally billed customers.  Same goes for things like delivery orders, possibly even production lots etc.

By going geographic we can assign ownership of a warehouse to an operating unit. and in any case our segments are geographic.

But this gave me a problem, and in trying to resolve it, I think I've come up with an elegant solution to both it and another problem.  The 2 problems relate to what happens when one Operating Unit, sells goods 'belonging' to another operational unit i.e. out of their warehouse. For this example I use Wellington and Central.

Wellington sells $100/$200 of goods (cost/sale) out of Centrals warehouse.  So centrals stock reduces by $100, but the corresponding sale goes on Wellingtons P&L.

At first I thought this was a selfmade problem, but when I looked deeper it revealed a second problem.  Not only is Wellington not paying for the goods, but their P&L is also not reflecting all the other P&L expenses they take advantage of at Central (e.g. Factory Labour, Depreciation, Freight etc).

So in order to resolve this in a Balance Sheet and P&L neutral way (not to mention stock costing), I thought about emulating the way we handle current intercompany and apply a transfer price, while keeping top level balances identical (IOW you can't profit just from selling stock to each other).

So in this scenario we'll assume intercompany pricing (as good as any to use for transfer pricing) and we end up with a journal entry that looks like this.


  | DR | CR | BU |  
-- | -- | -- | -- | --
Inventory |   | 100 | Central | Asset
Inventory | 100 |   | Wellington | Asset
Inter OU Contribution |   | 10 | Central | Cost of Sales – Factory Cost or split
Inter OU Contribution | 10 |   | Wellington |  
Inter OU Balances | 110 |   | Central | (effectively combined Debtor Creditor)
Inter OU Balances |   | 110 | Wellington | (effectively combined Debtor Creditor)

Note the effect of this transaction - Internally Wellingtons inventory increased by $100, Central's decreased by $100 but externally stock didn't change.

Externally the other 2 accounts will always balance to zero, but Wellington has paid $10 towards Central's overheads, and owes Central $110 for the stock it took. 

Periodically (say end of month) the internal OU Balance account could be reset to zero for each OU with either an internal subvention or cash/bank transaction, something like (assuming a single bank account and no actual payment made) although it is strictly unnecessary but useful for reflecting actual cashflow.

DR Bank 110 Central
CR Bank 110 Wellington
DR IOU Balances 110 Wellington
CR IOU Balances 110 Central


As for the rest of the related transactions they look the same - all against the Wellington OU

Delivery
DR Stock Output 100
CR Inventory 100

Invoice
CR Stock Output 100
DR Cogs 100

Sales CR 200
GST CR 30
Debtors DR 230

Payment
DR Bank / CR Debtors

So the benefits we have.
- More accurate P & L better reflecting the operating units actual costs
- No balance sheet or P & L effect at top level
- No cost effect (i.e. average cost doesn't change)
- 100% IFRS 8 Compliant with no required adjusting entries for reporting.

The only real downside I saw is you could possibly say is that COGS doesn't reflect the transfer price, in terms of measuring customer profitability at an OU level but when you think about it (and I did for a very long time), it shouldn't.  The extra $10 would have not been reflected if Central had sold directly, and Wellington has paid for that $10.  So from an entity accounting perspective I'm pretty sure we are straight.

Have I missed anything?
-- End mail

In addition, if you apply this concept right through to all the things that happen from both a segment and multicompany reporting perspective the you can have journal entries like such.

Management Fees CR 100 Head Office, DR 80 Wellington, DR 20 Central
IOU Payable DR 100 Head Office CR 80 Wellington, CR 20 Central

Essentially provided we keep the net balances of an account unchanged we can reallocate cost anywhere.  In the management fees case it is a gross simplification, because there would be a corresponding set of entries which are allocating the costs plus a contribution margin if any.

**Comment by JordiBForgeFlow** [comment]
@gdgellatly it is great! I played a bit with this concept in v7, but finally did not pursue the topic futher.

**Comment by gdgellatly** [comment]
@jbeficent I have a working alpha implementation.  It is very basic and has some mocked out methods but it works for the sale from one ou, with shipping from another.  https://github.com/gdgellatly/operating-unit/tree/operating_unit-ng . I was going to change name to avoid conflict, but realistically no one but me uses my repos anyway, and I don't put at apps so just reverted those changes.
