### ISSUE TITLE
Operating Unit Domain Security

### ISSUE THREAD

**Issue by gdgellatly** [OCA/operating-unit#106]
I was looking at security in relation to #104 and I think I have found a major mistake in the way this has been constructed.

If you take any record rule file you will notice an entry not unlike

```xml
    <record id="ir_rule_invoice_allowed_operating_units" model="ir.rule">
        <field name="model_id" ref="account.model_account_invoice"/>
        <field name="domain_force">['|', ('operating_unit_id','=',False), ('operating_unit_id','in',[g.id for g in user.operating_unit_ids])]</field>
        <field name="name">Invoices from allowed operating units</field>
        <field name="global" eval="True"/>
        <field eval="0" name="perm_unlink"/>
        <field eval="0" name="perm_write"/>
        <field eval="1" name="perm_read"/>
        <field eval="0" name="perm_create"/>
    </record>
```

Now ir.rule is kind of the opposite of assigning permissions.  In other words, perm_read = 1 translates as - when a user tries to read an invoice, disallow it.  So in this case you are effectively saying a User who is not part of an operating unit cannot read it, but can write to it, delete it and create it.

This is a bad example, as actually it might be desirable for users not to be able read another users invoices, but I think this code just end up copy pasted everywhere, with people thinking it gave read access.  Or maybe its by design?

**Comment by JordiBForgeFlow** [comment]
@gdgellatly Perhaps you're right. Perhaps the rule should apply to all: read, write, unlink, create.
