### ISSUE TITLE
[Feature Request] Sale price and cost price per operating unit?

### ISSUE THREAD

**Issue by vkk-steigend** [OCA/operating-unit#107]
Can we have a feature for capturing sale / cost price at operating unit level. Or in general can we have an operating unit dependent field similar to company dependent field?

**Comment by gdgellatly** [comment]
For sale and purchase price yes, I think it already exists. For costs, accounting standards prevent this in external reporting meaning I doubt there would be much uptake. In any case, you give yourself a hige headache considering transfers between units. Not really actionable so closing.
