### ISSUE TITLE
[10.0] Inventory Adjustment does not consider Operating Unit

### ISSUE THREAD

**Issue by vkk-steigend** [OCA/operating-unit#109]
While performing an inventory adjustment, operating unit is not set properly in journal entries. User's default operating unit is being used as OU in journal entry. Can be resolved by taking the OU if present in Stock Location.

**Comment by AaronHForgeFlow** [comment]
Hi @vkk-steigend 

The journal entries are supposed to use the operating unit in the stock move. There are two operating unit fields in the stock moves, one for the source location and one for the destination location. The operating unit in the stock_move is related to the location so it should take the same as the location's operating  unit. I was unable to recreate your issue, is it still happening for you?

**Comment by gdgellatly** [comment]
Probably not
