### ISSUE TITLE
New Sales Quotation without OU

### ISSUE THREAD

**Issue by w-mohsen** [OCA/operating-unit#111]
Dear All,

I have installed OU in Odoo 10 and I have created a user and granted him access to Sales User:All Documents group and assigned one OU to him  then I created a Quotation and I didn't see any  OU field in quotation and after creation,I checked the quotation from Admin account, I was able to see the OU field in the form and tree view but it was empty. 
I think the OU field should be visible and filled with default OU of the user and a user should able to select the OU if he has access to more than one OU.

After that, I have selected the checkbox of "Multi Operating Unit" and I was able to see the OU field  but the default OU is not selected by default during the creation and the quotation created with empty OU. Is the normal and this quotation under which OU will be? 

Please advise.

**Comment by AaronHForgeFlow** [comment]
Hi @w-mohsen 
The operating unit in the SO will be the operating unit of the team not the one of the user, please set the OU in the sale team:
![image](https://user-images.githubusercontent.com/19620251/40061628-acd4cdf6-5859-11e8-8c56-e43fa4f7590f.png)

**Comment by MohsenWaleed** [comment]
Many thanks @aheficent.
