### ISSUE TITLE
Operating unit on account journals

### ISSUE THREAD

**Issue by sbidoul** [OCA/operating-unit#118]
Why is the operating unit on account journal visible only on bank and cash journals?

https://github.com/OCA/operating-unit/blob/cbcc0a597c507efe3e94322d9f3016334770a3d7/account_operating_unit/views/account_journal_view.xml#L10-L13

Would there be any drawbacks to show it on all journals?

**Comment by JordiBForgeFlow** [comment]
Except for payments, the operating unit is generally derived from other sources. Manually in journal entries,  from the invoice, etc. But for payments, the payment method is the journal, and that's where the user decides what OU pays for an invoice.

For bank and cash, you could pay an invoice from OU A, with a payment method (Journal) from OU B. That will create additional self-balancing journal items in each OU.

Is that more clear?

**Comment by sbidoul** [comment]
That clarifies that constraint, thanks.

https://github.com/OCA/operating-unit/blob/cbcc0a597c507efe3e94322d9f3016334770a3d7/account_operating_unit/models/account_journal.py#L22-L28

I've a scenario where I would like each OU to have it's own sales journal. So I'm wondering if there would be any downside to setting an OU on sale/purchase/other journals too.

**Comment by JordiBForgeFlow** [comment]
Yes, I agree. We could leave the operating_unit_id as an optional field. And use a constraint that makes it required for bank/cash journals. Then we would need to review if we need additional security rules.

**Comment by sbidoul** [comment]
It looks that the record rule is there:

https://github.com/OCA/operating-unit/blob/cbcc0a597c507efe3e94322d9f3016334770a3d7/account_operating_unit/security/account_security.xml#L4-L14
