### ISSUE TITLE
[11.0]  stock_operating_unit: Permission denied at the locations created before the module installation

### ISSUE THREAD

**Issue by meigallodixital** [OCA/operating-unit#131]
I'm trying to migrate this module. Apparently the migration is direct from 10.0 with few changes.

Is it necessary for all locations to have an operational unit? It seems that if they do not have any unit configured gives read permission error. 

`(Document type: stock.picking.type, Operation: read) `

The locations without operating unit should not be seen by the whole company? If not, how would these be configured?

**Comment by AaronHForgeFlow** [comment]
The locations are seen for all stock users when they are not assign to any operating unit. But to configure them well it's better to assign them to an operating unit. 

Can you propose a PR so we can test? Will can put the WIP tag if you want. Thanks.

**Comment by meigallodixital** [comment]
I think there is something broken with permissions (probably my fault: \), because all users see the same thing. For example, a standard user with the assigned ou1 sees the locations of ou2 and ou3, but not the location without an operating unit. Same behavior as a user permissions in the three ou's.

I review the migration steps to 11.0 and upload a PR to see if anyone sees that I am doing wrong ... I am following these: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by AaronHForgeFlow** [comment]
That behavior is wrong. Not sure if there's a bug in the code or it is a configuration mistake.
 It's great to see  new collaborators in this repo :grinning:

**Comment by meigallodixital** [comment]
I correct myself. Only the warehouse created in installation fails. The new stores with blank OU appear for all, is what has confused me (had reinstalled and they lost the ou ...). It is only the one that is created in installation.

Could it be that this was created by the 'root' account?

**Comment by meigallodixital** [comment]
Pull request done. I hope I have done well without breaking anything ;)

The compilation on PR  fails because the account_operating_unit from #114  is not merged :( You must install it.

**Comment by gdgellatly** [comment]
Has a PR, seems resolved.
