### ISSUE TITLE
[11.0] procurement_operating_unit - Depends on the procurement module that does not seem to exist in v11

### ISSUE THREAD

**Issue by meigallodixital** [OCA/operating-unit#134]
I am trying to migrate the **purchase_operating_unit** module. This module depends on **procurement_operating_unit**, an this depends on the **procurement** module, which no longer exists in v11, but is integrated into **inventory**. Is this correct?

If it no longer exists, would **procurement_operating_unit** be removed and the permissions integrated into **inventory**?

**Comment by AaronHForgeFlow** [comment]
I have to take a deeper look into it, but I think procurement_groups still remain and there's some logic we have to analyze to check if it's consistence at OU level.

**Comment by meigallodixital** [comment]
The **procurement_operating_unit** module 'only' gives permissions on **procurement.model_procurement_order** model. 

Edit: Yes, it is removed on V11 -> https://www.odoo.com/es_ES/forum/ayuda-1/question/procurement-order-in-odoo11-135694

Edit 2: I do not know if there is a case of **procurement** without a **purchase**, but I understand that there may be **purchases** without **procurement** ... What do you think about moving all the **procurement** code in the **purchase** module to this one?

**Comment by AaronHForgeFlow** [comment]
Yes, it's removed as an entity, but procurement groups remain and the logic has to be consistent as OU level.

For testing purposes you can remove the dependency and try to migrate purchase_operating_unit.

**Comment by meigallodixital** [comment]
I was just doing it, and it works well.

I understand that the separation of modules cames for reuse with another modules like MRP (we don't have manufacturing)
