### ISSUE TITLE
installing operating unit on odoo 11

### ISSUE THREAD

**Issue by mnagy15** [OCA/operating-unit#143]

**Comment by mnagy15** [comment]
I am trying to install operating unit add on on odoo 11 but it gives errors   
I need installation guide

**Comment by meigallodixital** [comment]
What errors does the installation show you?

**Comment by mnagy15** [comment]
i changed the custom_addons path and it doesn't show the error again but module don't work on 11

**Comment by meigallodixital** [comment]
The base module only allows you to create operating units. I do not know what you expect or if the creation menu is not shown. You want to do?

**Comment by AaronHForgeFlow** [comment]
Please provide a clear way to reproduce the error on runbot so we can help you. Otherwise, the cause of the issue may be your implementation.

Regards.
