### ISSUE TITLE
[RFC] OU in POS (12.0 ideally)

### ISSUE THREAD

**Issue by elicoidal** [OCA/operating-unit#155]
Hi,
Is there any development/intention related for OU in POS? I could not find any in this repo but maybe some other repos might be looked into?

If not we might plan to use OU in one of our project and would need OU in POS. AFAICS, we would need to add the field/ACL in the following objects:
* pos.session
* pos.order

I am wondering about the payment methods and POS Product Categories.
Besides we will need to be careful with:
* the journals set up
* potential conflicts with accounting OU?

Any other idea/feedback?

**Comment by jacobus101** [comment]
Do you have any plans to develop in POS @MiquelRForgeFlow @AaronHForgeFlow @LoisRForgeFlow? thanks in advance!

**Comment by flotho** [comment]
Hi @elicoidal , @jacobus101 ,

Any work already started, I would like to implement this.

Regards

**Comment by AaronHForgeFlow** [comment]
From my side there is no plan to work on that. Feel free to propose anything :)

**Comment by jacobus101** [comment]
We bought the BroseInfo one published in app store because we were running out of time for the project, but we found that the module doesn't apply OU to journal entries so we quickly addapted it. We want to publish it but is completely mixed what we develop with the module that we bought, so we are very far from the PR here.

**Comment by ncaccia** [comment]
Hi @jacobus101 we discover the same problem, could you guide us on adapting the Broseinfo module? 

Thanks for your time!

**Comment by flotho** [comment]
Hi @ncaccia, did you tried my branch mentioned above.
It's working perfectly in production  with 6 different POS

**Comment by ncaccia** [comment]
Hi, @flotho
I will try it from your repo --> https://github.com/flotho/operating-unit/tree/12.0-ADD-pos-operation-unit/pos_operating_unit

Thanks for your help!

**Comment by ncaccia** [comment]
Hi @flotho, we are experiencing some troubles with the **team_id.operating_unit_id**, it seems that the team_id atribute is missing, but it is completed on the sales configuration. Do you how any idea how to solve this issue?

![image](https://user-images.githubusercontent.com/42478849/89592782-e5dad400-d823-11ea-91ae-bce732d8e774.png)


![image](https://user-images.githubusercontent.com/42478849/89592678-9d231b00-d823-11ea-917a-c64490df5e64.png)

thanks for your help!

**Comment by flotho** [comment]
strange, I have the field correctly defined : https://github.com/flotho/operating-unit/blob/12.0-ADD-pos-operation-unit/pos_operating_unit/models/pos_config.py#L19
maybe you don't have default operating unit defined on the user that is updating datas ?
