### ISSUE TITLE
Migration to v9 - Sprint P1

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/operating-unit#16]
This issue summarizes the development of the migration to v9 of priority 1 modules.
-  [x] operating_unit
-  [x] procurement_operating_unit - https://github.com/Eficent/operating-unit/tree/9.0-procurement_operating_unit. Pending PR to OCA.
-  [x] purchase_operating_unit - WIP https://github.com/Eficent/operating-unit/tree/9.0-purchase_operating_unit. Pending PR to OCA.
-  [x] account_operating_unit
-  [x] account_voucher_operating_unit  - WIP https://github.com/Eficent/operating-unit/tree/8.0-account_voucher_operating_unit. Assigned to @aheficent
-  [x] stock_operating_unit  - WIP https://github.com/Eficent/operating-unit/tree/9.0-stock_operating_unit
-  [x] stock_account_operating_unit  - WIP https://github.com/Eficent/operating-unit/tree/9.0-stock_account_operating_unit
-  [x] sale_operating_unit - Branch in v8: https://github.com/Eficent/operating-unit/tree/8.0-sale_operating_unit. Assigned to @aheficent
-  [x] sale_stock_operating_unit - Branch in v8: https://github.com/Eficent/operating-unit/tree/8.0-sale_stock_operating_unit. Assigned to @aheficent
-  [x] crm_operating_unit - Branch in v8: https://github.com/Eficent/operating-unit/tree/8.0-crm_operating_unit. Assigned to @darshan-serpent
-  [ ] sale_crm_operating_unit . Assigned to @darshan-serpent

**Comment by dreispt** [comment]
Maybe it's clearer if you organize in two lists.
Would you like to try using milestones - from what I've see that can work very well.
I suggest "9.0-sprint-P1" and "9.0-sprint-P2"

**Comment by JordiBForgeFlow** [comment]
Thanks @dreispt

**Comment by AaronHForgeFlow** [comment]
**account_operating_unit** merged :clap: 
 **crm_operating_unit** merged :clap: 
 **account_voucher_operating_unit** merged :clap: 
**procurement_operating_unit**: https://github.com/OCA/operating-unit/pull/29 merged :clap: 
**purchase_operating_unit**: https://github.com/OCA/operating-unit/pull/28 (Needs review)
**stock_operating_unit**: https://github.com/OCA/operating-unit/pull/31 merged :clap: 
**stock_account_operating_unit**: https://github.com/OCA/operating-unit/pull/21 (Depends on Stock OU)
**sale_operating_unit**: https://github.com/OCA/operating-unit/pull/22 (Depends on Sales Team OU )
**sale_team_operating_unit**: https://github.com/OCA/operating-unit/pull/35 merged :clap: 
**sale_stock_operating_unit**: https://github.com/OCA/operating-unit/pull/23 (Depends on Sale OU)
**sale_crm_operating_unit**: https://github.com/OCA/operating-unit/pull/33 (Needs review)

Next PR to merge: stock_operating_unit, sale_operating_unit
