### ISSUE TITLE
Migration to v9 - Sprint P2

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/operating-unit#17]
-  [ ] purchase_requisition_operating_unit (P2) - Branch in v8: https://github.com/Eficent/operating-unit/tree/8.0-purchase_requisition_operating_unit. Assigned to @darshan-serpent
-  [ ] mis_builder_operating_unit (P2) - WIP https://github.com/Eficent/operating-unit/tree/9.0-mis_builder_operating_unit. Assigned to @darshan-serpent => PR https://github.com/OCA/operating-unit/pull/38
-  [ ] mrp_operating_unit (P2). Assigned to @darshan-serpent => PR https://github.com/OCA/operating-unit/pull/39
-  [ ] purchase_request_operating_unit (P2) - Branch in v8: https://github.com/Eficent/operating-unit/tree/8.0-purchase_request_operating_unit. Assigned to @darshan-serpent 
-  [ ] purchase_request_procurement_operating_unit (P2) - Branch in v7: https://github.com/Eficent/odoo-operating-unit. Assigned to @darshan-serpent 
-  [ ] purchase_request_to_requisition_operating_unit (P2) - Branch in v7: https://github.com/Eficent/odoo-operating-unit. Assigned to @darshan-serpent 
-  [ ] purchase_request_to_rfq_operating_unit (P2) - Branch in v7: https://github.com/Eficent/odoo-operating-unit. Assigned to @darshan-serpent 
-  [ ] hr_payroll_account_operating_unit (P2) - Branch in v7: https://github.com/Eficent/odoo-operating-unit. => PR https://github.com/OCA/operating-unit/pull/25
-  [ ] hr_contract_account_operating_unit (P2) - Branch in v7: https://github.com/Eficent/odoo-. Assigned to @darshan-serpent
-  [x] hr_expense_operating_unit (P2) - Branch in v8: https://github.com/Eficent/operating-unit/tree/8.0-hr_expense_operating_unit. Assigned to @darshan-serpent => PR https://github.com/OCA/operating-unit/pull/30
-  [x] crm_claim_operating_unit (P2)  - Branch in v7: https://github.com/Eficent/odoo-operating-unit. Assigned to @darshan-serpent => PR https://github.com/OCA/operating-unit/pull/27
-  [ ] account_budget_operating_unit (P2)  - Branch in v8: https://github.com/Eficent/operating-unit/tree/8.0-account_budget_operating_unit. Assigned to @darshan-serpent => PR https://github.com/OCA/operating-unit/pull/37

**Comment by AaronHForgeFlow** [comment]
Migration Status at 11/02/2016:

**purchase_requisition_operating_unit**: https://github.com/OCA/operating-unit/pull/34 (Depends on purchase_operating_unit)
**mis_builder_operating_unit**: https://github.com/OCA/operating-unit/pull/38 (Depends on mis_builder)
**mrp_operating_unit**: https://github.com/OCA/operating-unit/pull/39 (Depends on procurement_operating_unit)
**purchase_request_operating_unit**: https://github.com/OCA/operating-unit/pull/41
**hr_payroll_account_operating_unit**: https://github.com/OCA/operating-unit/pull/25 (Depends on hr_contract OU)
**hr_contract_account_operating_unit**: https://github.com/OCA/operating-unit/pull/24 (Two more reviewers needed)
**crm_claim_operating_unit**. https://github.com/OCA/operating-unit/pull/27 (Two more reviewers needed)
**account_budget_operating_unit**: https://github.com/OCA/operating-unit/pull/37 (Reviewers needed)
