### ISSUE TITLE
Advise

### ISSUE THREAD

**Issue by blaggacao** [OCA/operating-unit#192]
@jbeficent Looks like I'm gonna join this effort and drop https://github.com/odoo/odoo/pull/19839/files

I might do kind of a intense sprint during the next few days while ensuring existing features of my solution and hope I can give some serious amount of valuable input. Hope stars are aligned and things can be merged quickly...

I'll be working on v12. Please ping the people who should take not of this and otherwise close, once acknowledged.

Anything I should know / take into account?

Best Regards,
David

**Comment by JordiBForgeFlow** [comment]
you're welcome to join! We are already migrating to v12. Please start by reviewing all open PR's.

**Comment by blaggacao** [comment]
There are some milestones in parallel, all in course. Are some outdated / abandoned? https://github.com/OCA/operating-unit/milestones

**Comment by JordiBForgeFlow** [comment]
Yes. Focus on v12

**Comment by blaggacao** [comment]
@jbeficent Would it be ~feasible~ thinkable to inherit `BaseModel`, detect on init if field `company_id` is present and inject `operating_unit_id` (+ generic business logic) in such case? I think this would somewhat reduce the need for maintaining so many modules / dependencies. (Same for the views, maybe on `js` or `qweb`).

```python
# Infer and adopt from company_id:
states={'draft': [('readonly', False)]})
```

```python
# Rather easy to generalize:
    @api.multi
    @api.constrains('operating_unit_id', 'company_id')
    def _check_company_operating_unit(self):
        for pr in self:
            if (
                pr.company_id and
                pr.operating_unit_id and
                pr.company_id != pr.operating_unit_id.company_id
            ):
                raise ValidationError(_('The Company in the Invoice and in '
                                        'Operating Unit must be the same.'))
        return True

    @api.multi
    @api.constrains('operating_unit_id', 'journal_id')
    def _check_journal_operating_unit(self):
        for ai in self:
            if (
                ai.journal_id.operating_unit_id and
                ai.operating_unit_id and
                ai.operating_unit_id != ai.journal_id.operating_unit_id
            ):
                raise ValidationError(_('The OU in the Invoice and in '
                                        'Journal must be the same.'))
        return True
```
We would be left with this type of business logic:
( I see how [this](https://github.com/odoo/odoo/issues/28549) would be extremely useful, in this case )
```python
    @api.multi
    def finalize_invoice_move_lines(self, move_lines):
        move_lines = super(AccountInvoice,
                           self).finalize_invoice_move_lines(move_lines)
        new_move_lines = []
        for line_tuple in move_lines:
            if self.operating_unit_id:
                line_tuple[2]['operating_unit_id'] = \
                    self.operating_unit_id.id
            new_move_lines.append(line_tuple)
        return new_move_lines
```

**Comment by blaggacao** [comment]
```python
    @api.multi
    @api.constrains('operating_unit_id', 'journal_id')
    def _check_journal_operating_unit(self):
        for ai in self:
            if (
                ai.journal_id.operating_unit_id and
                ai.operating_unit_id and
                ai.operating_unit_id != ai.journal_id.operating_unit_id
            ):
                raise ValidationError(_('The OU in the Invoice and in '
                                        'Journal must be the same.'))
        return True
```

This type of business logic. Is it fool proof in the sense that when the user's operating unit is changed, this it not enforced. Am I missing something?

**Comment by blaggacao** [comment]
For the individual business logic, I'm thinking of a possibility to inject them at module init tine through a  model switch case, this way transitioning logic could be transversally maintained in a single place (which is not only easier to maintain, but also gives a clearer picture of the neuralgic transitioning point).

**Comment by JordiBForgeFlow** [comment]
We have done some generalizing work on multicompany constraints here: https://github.com/Eficent/multicompany-fixes potentially applicable also to operating units.

We have tried to generalize, but bumped into several problems.

But you're free to try and experiement. We are happy to test working proposals that include unit tests. That would be a quality feedback to the project.

Would also welcome formal reviews of the open PR's. Not oriented to refactoring, please
