### ISSUE TITLE
Account Operating Unit module missing in v12

### ISSUE THREAD

**Issue by younismahsud** [OCA/operating-unit#198]
Do you have a plan to migrate account_operating_unit module to odoo v12?

**Comment by pedrobaeza** [comment]
Nobody has migrated yet. This is a voluntary work.

**Comment by AaronHForgeFlow** [comment]
@younismahsud There is a open Pull request here https://github.com/OCA/operating-unit/pull/149 and it is closed to be merged. More reviews are welcome.
