### ISSUE TITLE
Review Labels missing

### ISSUE THREAD

**Issue by dreispt** [OCA/operating-unit#2]
@oca GitHub reviews labels, such as "Needs Review" are missing.

**Comment by yvaucher** [comment]
Someone needs to play https://github.com/OCA/maintainer-tools/blob/master/tools/set_repo_labels.py

**Comment by yvaucher** [comment]
But first we might want to remove the labels
  '7.0': '000000',
  '8.0': '000000',

Using milestones instead ?

**Comment by dreispt** [comment]
I see some maintainers use labels and others use milestones.
I personally think milestones work better, and use them on the project' where I'm an active maintainer.
But at the moment no single truth here.

**Comment by yvaucher** [comment]
@dreispt thus removing them from the list could let the choice.

**Comment by pedrobaeza** [comment]
Added without 7.0 and 8.0 labels

**Comment by dreispt** [comment]
Thanks Pedro.
