### ISSUE TITLE
[RFC] sale_multi_operating_unit

### ISSUE THREAD

**Issue by max3903** [OCA/operating-unit#216]
Dependencies: sale_operating_unit, product_operating_unit, res_partner_operating_unit
License: AGPL-3

This module allows a user in an operating unit to request internal quote to another operating unit. 

# Usage

* Go to Sales
* Create a quotation for one of your OU customer
* Enter lines using products from your OU catalog
* Go to the "Internal Quotes" tab and enter the list of products and quantity that you need to quote from the other OU
* Send the internal quote

As a user in the other OUs

* Go to CRM
* A new lead has been created for the internal customer
* The description contains the delivery address and the list of products and quantity to quote
* Create a sale order from the lead, add your products, quantity and price
* Send the quote to the internal customer

# Technical Specifications

## res.company

- [x] Add a text field "Lead Description Template" (crm_lead_template) with a default value
```
{%% partner_shipping_id %%}
{% for line in line_ids %}
{%% line.name: line.qty line.uom_id.name %%}
{% endfor %}
```

## sale.order.quote.line

- [x] Add the object
- [x] Add a required char field "Description" (name)
- [x] Add a many2one field "Internal Quote" (quote_id) to sale.order.quote
- [x] Add a many2one field "Product" (product_id) to product.product. Filter the list of product with the one that belongs to the selected operating unit.
- [x] Add a float field "Quantity" (qty)
- [x] Add a many2one field "Unit of Measure" (uom_id) to uom.uom. Only show the field to the uom group.
- [x] Add a float field "Unit Price" (price_unit)
- [x] Add a float field "Subtotal" (subtotal)
- [x] Add an onchange on the product to set the name and uom_id like on the sale order line

## sale.order.quote

- [x] Add the object
- [x] Add an invisible char field "Name" (name)
- [x] Add a required many2one field "Operating Unit" (operating_unit_id) to operating.unit
- [x] Add a many2one field "Sale" (sale_id) to sale.order
- [x] Add an onchange method on the Operating Unit and Sale to set the name as "Name of the Sale - Name of the OU" like "SO0032 - NOC"
- [x] Add a readonly many2one field "Lead" (lead_id) to crm.lead. The field is invisible if not set.
- [x] Add a one2many field "Products" (line_ids) to sale.order.quote.line using quote_id
- [x] Add a selection field "State" (state) with New, Sent, Received and a clickable statusbar. When clicking on "Send", a CRM lead is created (if not already done) for the selected OU with the mapping provided in the solution section above.
- [x] Use the Lead Description Template of the company to generate the lead description
- [x] Add a constraint to have a unique quote per sale and per operating unit

## sale.order

- [x] Add a one2many field "Internal Quotes" (quote_ids) to sale.order.quote using sale_id
- [x] Add a tab "Internal Quotes" with the request_ids field

**Comment by Dangar-Serpentcs** [comment]
**Improved**

![Selection_031](https://user-images.githubusercontent.com/38550879/71414728-3b3fe780-267e-11ea-9d74-c75f412ba5f1.png)
