### ISSUE TITLE
Warehouse Shared Between Multiple OU's

### ISSUE THREAD

**Issue by osi-scampbell** [OCA/operating-unit#237]
Problem:
We have workflows that have multiple OU's sharing the same warehouse but currently that functionality is not supported in OCA/operating-unit

Solution:
Instead of converting operating_unit_id from Many2one to Many2many, we can make the option to allow all OU's to use a warehouse if the OU on the warehouse is not set. When we handle error checking, just add the criteria 'if warehouse_id.operating_unit_id'. This way, if the OU is not set on the warehouse, none of the ValidationErrors will be raised.

**Comment by max3903** [comment]
@JordiBForgeFlow @AaronHForgeFlow What do you think of this solution?

**Comment by JordiBForgeFlow** [comment]
I think that it's a good idea! @AaronHForgeFlow can you check the referenced PR's!

Thanks guys for all the proposals! It's great to see you involved in OU's.

**Comment by osi-scampbell** [comment]
@JordiBForgeFlow Thanks! We're happy to help, I'll request @AaronHForgeFlow as a reviewer on those PR's.
