### ISSUE TITLE
[12] stock_account_operating_unit BUG: Error on moving more than 1 product

### ISSUE THREAD

**Issue by dkrimmer84** [OCA/operating-unit#256]
I would like to refer to the following line: 
https://github.com/OCA/operating-unit/blob/12.0/stock_account_operating_unit/model/stock_move.py#L56

saying that: 

> Generate accounting moves if the product being moved is subject to **real_time valuation tracking**

Well, this is exactly not the case. The module throws an technical error as soon as you try to move more than 1 product (for instance in an internal transfer from one location to another)

**On runbot you can reproduce the error / bug:**
Create a  product and assign it to a category that's Inventory Valuation is set to "real time". (On runbot it's set to "manual" as default, that's why it's working first). 

But as soon as you switch the product category to "**real time**", you can only move one single product. If you try to move more than 1, following error is thrown: 

`File "/path/stock_account_operating_unit/model/stock_move.py", line 87, in _action_done
    'stock_move_id': self.id,
  File "/path/odoo/fields.py", line 2888, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: stock.move(113, 114)`

@AaronHForgeFlow

**Comment by nikul-serpentcs** [comment]
@AaronHForgeFlow @dkrimmer84 Please close this issue.
