### ISSUE TITLE
[12.0] Default Operating Unit Res User Multi-Company

### ISSUE THREAD

**Issue by osi-scampbell** [OCA/operating-unit#270]
We previously tried to make the default_operating_unit_id a company dependant field but upon further testing it was discovered that this feature created issues. For more details see the PR where we roll back this change here: #247. The requirement that we have not satisfied yet is for users who may belong to one OU in Company 1 and another in Company 2. Currently, the default_operating_unit_id stays the same for users regardless of which company they are logged in under.

**Comment by max3903** [comment]
ping @AaronHForgeFlow

**Comment by AaronHForgeFlow** [comment]
It is ok to me to add that feature as long we solve all the incompatibilities that comes up. Many PRs were red because of that and I don't like to break anything.

**Comment by osi-scampbell** [comment]
@AaronHForgeFlow Ahhh I see, so maybe the solution is we open a [WIP] PR to see where the repo has its incompatabilites, then make PR's to change those modules affected?

**Comment by AaronHForgeFlow** [comment]
> @AaronHForgeFlow Ahhh I see, so maybe the solution is we open a [WIP] PR to see where the repo has its incompatabilites, then make PR's to change those modules affected?

Yes, agree with that. For some reason the PR that added this feature  was green, but then after the merge, some PRs were failing for unknown reasons. I remember a fix in module stock operating unit  that was causing an unrelated error in purchase_request_operating_unit, and the logs were not clear. Let's see now.
