### ISSUE TITLE
[13.0] account_operating_unit : The OU in the Move and in Journal must be the same.

### ISSUE THREAD

**Issue by newtratip** [OCA/operating-unit#284]
I have create 1 user for default OU "Main Operating Unit"
![Selection_490](https://user-images.githubusercontent.com/24691983/81197730-d365ba00-8fea-11ea-8e54-f208a692799b.png)

and create journal customer invoice for OU "B2B" and customer invoices2 for OU "Main Operating Unit"
![Selection_491](https://user-images.githubusercontent.com/24691983/81198299-846c5480-8feb-11ea-863d-df4a0543ee94.png)

I create customer invoice from sale order, the system show error "The OU in the Move and in Journal must be the same."
![Selection_492](https://user-images.githubusercontent.com/24691983/81198574-d7dea280-8feb-11ea-942d-3202f3d28380.png)

I think when create invoice the system pull journal customer invoice (B2B) and OU Main Operating Unit which OU not match

Can someone help for this ?

**Comment by AaronHForgeFlow** [comment]
Hi @newtratip . Thank you for reporting this. Do you know if you rPR https://github.com/OCA/operating-unit/pull/283 solves this?

**Comment by newtratip** [comment]
Closed. This is fix https://github.com/OCA/operating-unit/pull/283.
