### ISSUE TITLE
[13.0] New feature "DROPDOWN OU AS MULTI-COMPANIES"

### ISSUE THREAD

**Issue by AntoniRomera** [OCA/operating-unit#285]
I would like to propose adding the OUs as a dropdown as the multi-companies or within the multi-companies below the company associated with the OU.

 
This functionality had been thought?

Does anyone have that need or see it as useful?

**Comment by AaronHForgeFlow** [comment]
This would be a nice improvement. It is not implemented because it is far from being an easy task. Any proposals will be welcome for sure.

**Comment by AntoniRomera** [comment]
PR #288

**Comment by unique4** [comment]
Any update on this issue guys?

**Comment by AntoniRomera** [comment]
Sorry, I forgot to close this issue for my part, at the end I don't have time to develop it, if someone wants to continue it go ahead.
