### ISSUE TITLE
[12.0] stock_operating_unit dependent only on operating_unit

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/operating-unit#289]
i need this functionality only to manage warehouse restrictions, why there is in dependencies also account_operating_unit, why not use only operating_unit?

**Comment by AaronHForgeFlow** [comment]
Could you confirm the module works without that dependency?That dependency was added in v7.0 (stick depends on account in that version). Probably is not needed anymore and should have been removed in the migration. But that needs to be tested first. If you create a PR I will review.

**Comment by andreampiovesana** [comment]
it work!
thanks

Andrea Piovesana Linux Mint 19.3www.pnlug.it



Il giorno gio 21 mag 2020 alle ore 14:05 Aaron ForgeFlow <
notifications@github.com> ha scritto:

**Comment by andreampiovesana** [comment]
i did the PR
https://github.com/OCA/operating-unit/pull/290
