### ISSUE TITLE
Duplicate repo with brand

### ISSUE THREAD

**Issue by AntoniRomera** [OCA/operating-unit#292]
Hello,

I would like to know if this module is very different from brand because in my opinion they do the same and it is duplicating.

**Comment by AaronHForgeFlow** [comment]
Hi,

They are different things.

An Operating Unit (OU) is an organizational entity part of a company, but that operates as an independent unit. Organizationally, an Operating Unit divides a company from a Business/Divisional axis, while Departments divide a company from a functional axis perspective.

I am not use to brand repo but branding, by definition, is a marketing practice in which a company creates a name, symbol or design that is easily identifiable as belonging to the company.
