### ISSUE TITLE
[12.0] Why not having a default operating unit in the existing sales teams?

### ISSUE THREAD

**Issue by BT-rmartin** [OCA/operating-unit#316]
Dear community, 

When I have installed sale_operating_unit with an own module not depending on operating units at all, but creating a SO in its tests, I'm receiving an error due to this [constraint](https://github.com/OCA/operating-unit/blob/12.0/sale_operating_unit/models/sale_order.py#L45). 

This is mainly due to the fact that the sales team has no operating unit, whilst the SO is [given the one from the user](https://github.com/OCA/operating-unit/blob/12.0/sale_operating_unit/models/sale_order.py#L17). 

I wonder why we don't put Main Operating Unit as the operating unit for the existing [demo Sales Team (Europe)](https://github.com/odoo/odoo/blob/12.0/addons/sales_team/data/sales_team_demo.xml#L5).
I guess it's due to the fact that this is reused from odoo business data, then we would end up with default [Sales Team (Sales) ](https://github.com/odoo/odoo/blob/12.0/addons/sales_team/data/sales_team_data.xml#L4) having it as well.
Nevertheless, it would be similar to what it's already there for users. [Admin user gets Main Operating Unit assigned by default,](https://github.com/OCA/operating-unit/blob/12.0/operating_unit/data/operating_unit_data.xml#L10) so why not having also the existing sales team assigned to it?. In any of the cases it's required so for me it follows the same reasoning. 

Maybe this is a problem of my tests, that I'm doing with user Admin, and not creating any sales team, but allowing odoo to use what it has. 

If this is not feasible, I have like a few alternatives:
1- Not assigning Main Operating Unit to Admin user
2- Assigning Main Operating Unit to Europe Sales Team
3- Change the [constraint](https://github.com/OCA/operating-unit/blob/12.0/sale_operating_unit/models/sale_order.py#L45) so it only raises when both SO and Sales Team have an operating unit assigned and they are different
4- Change completely my tests to always use another user and create a Sale Team if I want to create SOs. But I would say this problem is not only in my tests but also in some other OCA repos. 

I would go for 2 or 3. Could you please give me your inputs? Did you experience some problem like this?

Thanks in advance

@AaronHForgeFlow @JordiBForgeFlow @gdgellatly @MiquelRForgeFlow @LoisRForgeFlow @darshan-odoo @sudhir-serpentcs

**Comment by gdgellatly** [comment]
Well to be honest I long since forked this project. I think for demo data we can just update the business data in a demo file. Doesn't matter that it is main data part of Odoo, it will only load for demo purposes then nothing changes for users.

**Comment by AaronHForgeFlow** [comment]
I am ok with option 2. Nothing changes for users but would ease the test automation.
