### ISSUE TITLE
14.0 stock_account_operating_unit and stock valuation layers

### ISSUE THREAD

**Issue by gdgellatly** [OCA/operating-unit#381]
So we did a rough migration of stock_account_operating_unit but in testing I noticed that we might have to consider svl's in largely the same way we consider stock move lines.

Am I right? Thoughts?

\cc @JordiBForgeFlow @RujiaL

**Comment by AaronHForgeFlow** [comment]
Good point. I think it could be computed based on the related stock move. If it is an incoming move then take the operating unit of the destination location. Then if it is an outgoing move we could take the source location operating unit. For transfers between operating units we may need then a external location that helps to create an outgoing layer and then an incoming.
