### ISSUE TITLE
[Question] res.partner in operating unit?

### ISSUE THREAD

**Issue by Mat-moran** [OCA/operating-unit#408]
Hi, 

I am thinking about the necessity of the `res.partner` selection in the definition of the operating unit. 
Can somebody explain the sense of that?

Thanks in advance. Regards!

**Comment by AaronHForgeFlow** [comment]
It is the same concept as the partner in the company. For example, when you create a customer invoice, it is issued by the operating unit partner, and the customer with see the contact details of the operating unit.
