### ISSUE TITLE
[14.0] contract_operating_unit: The license LGPL-3 conflicts with one of its dependencies.

### ISSUE THREAD

**Issue by dreispt** [OCA/operating-unit#427]
Module can't be registerd on the App Store:

> contract_operating_unit: The license LGPL-3 conflicts with one of its dependencies. Please make sure that you comply with the licenses compatibility. See our FAQ at https://apps.odoo.com/apps/faq#maintainer_faq_04 .

**Comment by AaronHForgeFlow** [comment]
Fixed in https://github.com/OCA/operating-unit/commit/71f9c177904e89936c09d9763618a29b49db46e1
