### ISSUE TITLE
Operating unit for Point Of Sale

### ISSUE THREAD

**Issue by labib66** [OCA/operating-unit#433]
**Is your feature request related to a problem?**
i can't make operating units as self balanced

**Describe the solution you'd like**
develop operating unit for pos

**Comment by AaronHForgeFlow** [comment]
You can begin by reviewing this PR https://github.com/OCA/operating-unit/pull/286

There is an issue already for this: https://github.com/OCA/operating-unit/issues/155 so better to follow up there if needed
