### ISSUE TITLE
how i can transfer products between different OU 2 location or warehouse

### ISSUE THREAD

**Issue by alielnagar** [OCA/operating-unit#435]
stock_operating_unit 14 
odoo 14

i can't make stand alone location without OU to make a internal transfer direct or make internal transfer by routes and rules 
please tell me 
how to make transfer between two operating unit    without admin doing this 
thank you

**Comment by AaronHForgeFlow** [comment]
Why you can't? An inventory user should be able to to those transfers. And the manager should be able to create the location without operating units, and the routes.

**Comment by alielnagar** [comment]
I am administrator and have acess to all ou by security and manager in ou 
But i cant create stand alone location witout ou 
I make work around by import location without ou 
Please fix it 
I working on odoo 14 
I install 
account_financial_report_operating_unit

account_operating_unit

analytic_operating_unit
analytic_operating_unit_access_all

operating_unit

operating_unit_access_all

product_operating_unit

purchase_operating_unit

purchase_operating_unit_access_all

sales_team_operating_unit

stock_operating_unit

stock_operating_unit_access_all

Thank you

**Comment by gdgellatly** [comment]
I have v14, this just works. No need for admin, don't even really need special routes, just need access to both OU's. They just create an internal transfer. But I imagine for more process oriented environments the routes would be simple enough via a Transit location.

**Comment by alielnagar** [comment]
the problem in case with the tow users have access to only his ou .

**Comment by AaronHForgeFlow** [comment]
You are transferring from a location with Operating unit 1 (OU1) to a transit location and then another tranfer from this transit location to another location with operating unit 2(OU2), right? Can you reproduce the error in runbot?
