### ISSUE TITLE
Inventory adjustment and operating unit / Analytic account

### ISSUE THREAD

**Issue by dominiquekonsuntack** [OCA/operating-unit#458]
Is there a module so that inventory adjustment will have operating unit ? - that will in turn pass in the journal entry ?
I haven't found any module with this functionality.

**Comment by AaronHForgeFlow** [comment]
The operating unit is the location using the module stock_operating_unit. The module stock_account operating unit should add the operating unit the operating unit on the stock valuation journal entries.
