### ISSUE TITLE
Operating Unit overwrite incorrect in purchase operating unit - uses previous operating unit

### ISSUE THREAD

**Issue by gdgellatly** [OCA/operating-unit#459]
https://github.com/OCA/operating-unit/blob/068418afedb673b2e499122c193106fb19cf31ad/account_operating_unit/models/account_move.py#L16-L23

https://github.com/OCA/operating-unit/blob/068418afedb673b2e499122c193106fb19cf31ad/purchase_operating_unit/models/account_invoice.py#L41-L52

If you are also writing the move and changing the operating unit this code uses the prior operating unit because it browses the previous move record as the new vals are not yet written. This is common when using purchase autocomplete from an emailed invoice where the default is for a different OU.

This then triggers the shown constraint error.

EDIT: Referenced wrong code initially

**Comment by AaronHForgeFlow** [comment]
I see. Do you have a solution for that? Perhaps override the purchase autocomplete feature so it selects the correct operating unit will work.

**Comment by gdgellatly** [comment]
@AaronHForgeFlow The problem isn't the autocomplete, actually that works perfectly. The problem is if the invoice exists with a different operating unit BEFORE autocomplete (incoming email, default ou is different to purchase ou for example), when the write is called, it will try and create the move lines before writing the change. The only solution I have had to date is a stupid workaround.

```
    def write(self, vals):
        """
        Workaround to stop constraint error in OU with autocomplete"""
        if (
            not self._context.get("write_ou")
            and self.operating_unit_id
            and "operating_unit_id" in vals
        ):
            ou_id = vals.pop("operating_unit_id")
            self.with_context(write_ou=True).write({"operating_unit_id": ou_id})
        return super().write(vals)
```

**Comment by AaronHForgeFlow** [comment]
Will removing the default operating unit in the invoice work?

**Comment by gdgellatly** [comment]
Hi,

I don't think so. It is just another workaround. But setting a default is kind of a 2 edged sword anyway and we should probably remove it, or remove constraints, security associated with it. Because move lines should be able to be applied to different operating units in the same move. (e.g. I got an invoice for 2 PO's for 2 different operating units). I almost feel like the move OU should be a computed field off the lines, not vice versa as it effectively is now or even just not exist, but that has its own problems.

As it stands we have this weird thing where an OU is not set on the move, a user can open the move, see the totals, but not see the lines for which they are not entitled.

The problem is always going to be using old data to force the Operating unit. I actually think it might be better just not to set the OU in create of the move line, if the OU is already in the vals at create time. We should rely on onchanges, the same as for every other field in move lines.
