### ISSUE TITLE
journal Sequences error in vendor payment (account_operating_unit)

### ISSUE THREAD

**Issue by alielnagar** [OCA/operating-unit#460]
## Module
account_operating_unit

## Describe the bug
i test the scenario on clean database when i found it in the production database) 
i have a big problem 
i have two journal 
cash with sequence 1cah 
bank with sequence bnk

after install  account_operating_unit in (clean database)
when i made first vendor payment and select the cash journal the document seq is CSH1/2022/02/0001
when i made second vendor payment and select the cash journal(same journal) the document is BNK1/2022/02/0001 
why it changed to bnk1 (i don't know ) but still registered to  cash journal 
when i made third vendor payment, this error msg (Posted journal entry must have an unique sequence number per company.
Problematic numbers: BNK1/2022/02/0001)

## To Reproduce
just install the module on clean database
Odoo 14.0-20220224 (Community Edition)

1.make 3 vendor payment 
 i setup 2 journal cash and bank without outstanding payment account

**Comment by alielnagar** [comment]
after update odoo on clean data base the problem gone 
please check it to devoid it 
thank you

**Comment by AaronHForgeFlow** [comment]
All right. Thanks.
