### ISSUE TITLE
[14.0] account_operating_unit compatibility with sale_advance_payment

### ISSUE THREAD

**Issue by kh-badep** [OCA/operating-unit#462]
In this part of code it is assumed that active_model is 'account.move' (payment done from an invoice) or none.  Which is not the case. Using sale_advance_payment where activel_model is 'sale.order' is one example of it.

https://github.com/OCA/operating-unit/blob/068418afedb673b2e499122c193106fb19cf31ad/account_operating_unit/models/account_payment.py#L28

There should be a test if active_model is indeed 'account.move' before browsing the invoice, or else it will throw a reference error. Or even better, browse the active objects with self.env[self._context.get("active_ids")].browse(self._context.get("active_ids")) and use its operating_unit_id for the same logic. This way it will work even for sale orders and purchase orders.

Reproducing the error is quite easy:

1. Install account_operating_unit
2. Install sale_advance_payment, purchase_advance_payment or any module that enables making payments from other classes
3. Make an advance payment from a sale order

**Comment by AaronHForgeFlow** [comment]
Thanks for reporting. Will you create a PR with the fix?

**Comment by kh-badep** [comment]
Yes. I'll be going with the second approach so that we can propagate 'operating_unit_id' from whatever document is creating the payment.

**Comment by kh-badep** [comment]
I just checked and there is already a PR with the first approach suggested here: https://github.com/OCA/operating-unit/pull/456.

I'm making a PR with the second approach here: https://github.com/OCA/operating-unit/pull/463, but to be honest I don't know if it's really needed.
