### ISSUE TITLE
[14.0] operating_unit - Default operating unit for new public user template ignored

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/operating-unit#488]
## Describe the bug
Operating units are assigned to new users regardless of settings in user "default"

## To Reproduce
**Affected versions**: supposedly all versions

1. activate "Default access rights" in General settings
2. set any (or no) operating unit as "default operating unit" and/or "operating unit" in user "default"
3. create new user

**Current behavior**
All operating units are assigned to new user regardless of the settings in user "default"

**Expected behavior**
The values should be set according to those in Default User Template

**Additional context**
[Video](https://recordit.co/RtypjHGIoq)

**Comment by AshishHirapara** [comment]
Fix: https://github.com/OCA/operating-unit/pull/491

**Comment by francesco-ooops** [comment]
fixed for 14 and 15
