### ISSUE TITLE
stock_account_operating_unit   -Account entry lines bug

### ISSUE THREAD

**Issue by isszero06** [OCA/operating-unit#498]
when transfer more than one product the journal entry created for the first product only by unit price not total price

**Comment by AaronHForgeFlow** [comment]
Can you explain it more? which version do you get the error? Clear steps to reproduce and expected results.

**Comment by isszero06** [comment]
١٣

في السبت، ٢٠ أغسطس ٢٠٢٢ ٨:٣٣ م Aaron ForgeFlow ***@***.***>
كتب:

**Comment by isszero06** [comment]
version 13

1- create internal transfer with the following lines

item    unit cost is       qty

product(1)   10             4
product(2)   12              3

when post transfer the system create only journal item for the first line
(product"1") by total amount 10 only ie unit value not total value when
generate journal item

also no jurnal item for product(2) only for the first line

**Comment by AaronHForgeFlow** [comment]
The internal transfer is between two different operating units, right?

**Comment by isszero06** [comment]
Yes, it is.

في السبت، ٢٠ أغسطس ٢٠٢٢ ٩:٢٨ م Aaron ForgeFlow ***@***.***>
كتب:
