### ISSUE TITLE
repo readme.md

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/operating-unit#505]
Hi, would it be possible to fix the readme.md for this repo to align it to the other repos? this is how 14 appears:

![image](https://user-images.githubusercontent.com/55489873/189143122-f3d45eb3-f226-4493-a483-df926aad3eb8.png)

I also see in v12 and 13 there are still links to transifex

**Comment by francesco-ooops** [comment]
@AaronHForgeFlow could you take a look? thanks!

**Comment by francesco-ooops** [comment]
@AaronHForgeFlow @OCA/accounting-maintainers gentle reminder

**Comment by francesco-ooops** [comment]
@sbidoul could I ask you for your help on this as well?

**Comment by sbidoul** [comment]
Nope, you've exhausted my quota for the day :)

But running `pipx run copier update` and checking the answers to the various questions should help.

**Comment by francesco-ooops** [comment]
ok then I'll resort back to @AaronHForgeFlow 😬

please? those broken icons break my heart 💔
