### ISSUE TITLE
User access not working for reports ?

### ISSUE THREAD

**Issue by victor-champonnois** [OCA/operating-unit#579]
## Module
operating_unit and project_operating_unit

## Describe the bug
A user can see other's operating units projects in the project reporting.

You can check the full example in this runboat : http://oca-operating-unit-14-0-f2ec2199c7ec.runboat.odoo-community.org/web#action=70&model=res.users&view_type=list&cids=1&menu_id=4

Log in as User1 with login "test@test.test" and password "test".

## To Reproduce
**Affected versions**:14

1.Remove all special rights regarding "operating units" to Administrator
2.Create an internal user and assign them a new operating unit (User1 in the runbota example, with OU "test")
3. With this user, create a project ("test" in the example) and a task
4.Log in as Admin, and go to Project>Reporting : you can see the projects "test" created by User1

**Expected behavior**
Admin should not see projects created by User1 in the reporting.

**Additional context**
In the runboat.

**Comment by hurrinico** [comment]
@victor-champonnois Have you fixed the problem?
I'm having a similar issue. It seems like the rule is computed when you change group on user.

**Comment by victor-champonnois** [comment]
@hurrinico Sorry no I didn't find the time
