### ISSUE TITLE
Default branch in operating-unit repo

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/operating-unit#611]
@OCA/community-maintainers  can you please move the default branch on this repo to be 16.0? I think I don't have permissions to do so. Thanks in adavance!

**Comment by StefanRijnhart** [comment]
@OCA/accounting-maintainers should have permissions to change the default branch on this one.

**Comment by grindtildeath** [comment]
@StefanRijnhart I just checked [Changing default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch) but although I'm part of accounting PSC, I don't have access to the repositories settings

**Comment by grindtildeath** [comment]
I guess we need a PR to change that? https://github.com/OCA/repo-maintainer-conf/blob/master/conf/repo/operating.yml#L15

**Comment by StefanRijnhart** [comment]
Ah good find! I totally missed this. Here is the announcement: https://odoo-community.org/groups/contributors-15/contributors-1199828?mode=thread&date_begin=&date_end=

**Comment by AaronHForgeFlow** [comment]
Thanks for the help! I will create a PR to update this https://github.com/OCA/repo-maintainer-conf/blob/master/conf/repo/operating.yml

**Comment by AaronHForgeFlow** [comment]
https://github.com/OCA/repo-maintainer-conf/pull/14

**Comment by StefanRijnhart** [comment]
It worked! Thanks @AaronHForgeFlow
