### ISSUE TITLE
How to get operating_unit_id in move line when importing bank_statement_line with online method like Ponto?

### ISSUE THREAD

**Issue by whulshof** [OCA/operating-unit#655]
I have merged the PR to get account_operating_unit into my 16.0 server. When I try to import my bank statements, I'm getting the general error message, that all move lines should have an operating_unit_id.
How do I get the operating_unit_id in the move lines? Is there a module or a config for it? Or do we just have to create a bank_statement_operating_unit module?

**Comment by AaronHForgeFlow** [comment]
account_operating_unit is still work in progress but in any case that part is not covered in the module, probably a new module is needed.

**Comment by whulshof** [comment]
OK, I had a look into 12.0 and 14.0 and I can't find anything looking like it. For 10.0 I made modules for a lot of these edge cases, but it will not be of use here anymore. Nothing planned?

**Comment by AaronHForgeFlow** [comment]
Nothing planned on my side, but it would be an interesting new feature.

**Comment by whulshof** [comment]
I also have made a module, that makes it possible to distribute cost/revenue in invoices to several operating_units. That one will have to be refactored because of the removal of the invoice_line object, but further would be very useable.
Would that be interesting do you think?

**Comment by AaronHForgeFlow** [comment]
what is the business scenario for that case?
