### ISSUE TITLE
Port to 16.0

### ISSUE THREAD

**Issue by Stephanvandenberg** [OCA/operating-unit#696]
module: sale_operating_unit
version: 14.0

Dear OCA contributors. Are you planning to port this module to 16.0 any time soon? If not I will start it - are you open for a PR in that case?

**Comment by hbrunn** [comment]
please consult https://github.com/OCA/operating-unit/issues/509 for already started migrations. There you'll find https://github.com/OCA/operating-unit/pull/600 which looks a bit orphaned, but you can base your migration on that
