### ISSUE TITLE
[9.0] [stock_operating_unit] not able to set Requesting Operating Unit

### ISSUE THREAD

**Issue by serpentcs-dev1** [OCA/operating-unit#75]
@aheficent Hello Aaron!! Request Operating Unit in the stock picking does not seems to work, the OU is initially set on the picking_type onchange but when you then try to save the picking it disappears. Is this behavior normal?  

Below I have attached two screenshots before and after saving the record.

![before_save](https://user-images.githubusercontent.com/20109026/27271757-257ee554-54e4-11e7-87ff-d29604afbf16.png)

![after_save](https://user-images.githubusercontent.com/20109026/27271756-2540997a-54e4-11e7-847d-8907e61f3ccd.png)

**Comment by AaronHForgeFlow** [comment]
hmmm it seems that we need to backport the fix from branch 10.0 https://github.com/OCA/operating-unit/pull/66

**Comment by AaronHForgeFlow** [comment]
I was wrong, the problem is different. It was related with onchange methods won't work for readonly fields. I proposed a solution here: https://github.com/OCA/operating-unit/pull/76

If this is ok I'll do the same for v10

**Comment by serpentcs-dev1** [comment]
Yes, it was regarding the onchange on the readonly field.

The issue is resolved in #76
