### ISSUE TITLE
[10.0] operating unit field on invoice should be readonly in non draft states

### ISSUE THREAD

**Issue by sbidoul** [OCA/operating-unit#77]
How to reproducte:
- create an invoice with operating unit
- validate the invoice
- the operating unit field is still modifiable

Expected behaviour:
- the operating unit should not be modifiable on a validated invoice

The same rule as other invoice fields must apply

**Comment by AaronHForgeFlow** [comment]
I agree @sbidoul we will fix this

**Comment by AaronHForgeFlow** [comment]
Closing this as PR is merged
