### ISSUE TITLE
Error When i Try to Create New Quotation

### ISSUE THREAD

**Issue by aitlamsali** [OCA/operating-unit#93]
Hi;

When i attach a user to his own UO and i connect with hiw account to make a quotation i got this error :

Odoo Warning - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: crm.team, Operation: read)

**Comment by aitlamsali** [comment]
Hi;

When i attach a user to his own UO and i connect with hiw account to make a quotation i got this error :

Odoo Warning - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: crm.team, Operation: read)

**Comment by aitlamsali** [comment]
Hello could you help me please ?

**Comment by AaronHForgeFlow** [comment]
Hi @aitlamsali Thank you for your report. Which Odoo version are you using. It seems to me that user should belong to group `Sales / User: Own Documents Only` Does the user belong to that group or Sales Manager group?

**Comment by w-mohsen** [comment]
Hi @aheficent I have the same issue in Odoo 10 and I got the same error when the user belong to Sales / User: Own Documents Only group and when I change it to User: All Documents group, I was able to create quotation / Sale orders.

 Please advise.

**Comment by AaronHForgeFlow** [comment]
@aitlamsali  @w-mohsen Thank you for reporting this issue. Can you check this PR https://github.com/OCA/operating-unit/pull/116? Thanks
